export const HOME_COPY = {
  zh: {
    nav_download: '下载 App',
    hero_title_1: '吨',
    hero_title_2: '吨',
    hero_title_3: '吨',
    hero_subtitle: '不带道具，也能玩到散场',
    hero_feature: '派对神器 · 防误触 · 拒绝冷场',
    hero_points: ['14 款游戏', '离线可玩', '无广告'],
    highlights_eyebrow: '为真实派对而生',
    highlights_title: '少解释，多尽兴。',
    highlights_intro: '开局快，不冷场。',
    highlights: [
      ['打开就玩', '规则和道具都已准备好。'],
      ['完全离线', '地下室、露营地、弱网环境，照样开局。'],
      ['醉酒友好', '更大的触控区域，更少的操作步骤。'],
      ['14 种玩法', '骰子、抽牌、点名与破冰，一站集齐。'],
    ],
    grid_title_prefix: '派对游戏',
    grid_title_suffix: 'All-in-One',
    grid_desc: '不管是真心话还是大冒险，一个 App 拯救所有局。',
    cta_main: '告别复杂的规则解释，',
    cta_highlight: '防误触',
    cta_suffix: '设计，让派对更尽兴。',
    cta_lead: '告别复杂的规则解释',
    cta_badge: '防误触设计',
    cta_title: '让派对更尽兴',
    store_badge_lead: '前往',
    btn_download: 'App Store 下载',
    feat_ios: 'iOS 独占',
    feat_ads: '无广告',
    feat_drunk: '防醉酒模式',
    card_hint_front: '点击查看规则',
    card_hint_back: '点击返回',
    rules_title: '规则',
    a11y_game_card: '{name}，醉酒指数 {level}，预计时长 {duration}',
    a11y_drunk_level: '醉酒指数 {level} / 5',
    a11y_skip: '跳到主要内容',
    a11y_screens: 'App 截图',
    a11y_screens_prev: '查看上一张截图',
    a11y_screens_next: '查看下一张截图',
    a11y_screens_pagination: '截图位置指示',
    a11y_screen_menu: '主菜单截图',
    a11y_screen_game: '{name} 游戏截图',
    a11y_nav: '主导航',
    a11y_footer: '页脚',
    a11y_language: '语言',
    footer_rights: '© 2026 CHUGCHUG APP',
    footer_privacy: '隐私政策',
    footer_contact: '联系我们',
    inapp_title: '请在 Safari 或默认浏览器中打开',
    inapp_subtitle: '检测到当前处于内置浏览器中，无法直接跳转 App Store',
    inapp_step1_label: '1. 点击右上角菜单按钮',
    inapp_step1_code: '•••',
    inapp_step2_label: '2. 选择「在 Safari 中打开」或「在默认浏览器中打开」',
    inapp_btn_copy: '复制网页链接',
    inapp_copied: '已复制链接！',
    inapp_btn_close: '我知道了',
  },
  'zh-Hant': {
    nav_download: '下載 App',
    hero_title_1: 'Chug',
    hero_title_2: 'Chug',
    hero_title_3: '',
    hero_subtitle: '不帶道具，也能玩到散場',
    hero_feature: '派對神器 · 防誤觸 · 拒絕冷場',
    hero_points: ['14 款遊戲', '離線可玩', '無廣告'],
    highlights_eyebrow: '為真實派對而生',
    highlights_title: '少解釋，多盡興。',
    highlights_intro: '開局快，不冷場。',
    highlights: [
      ['打開就玩', '規則和道具都已準備好。'],
      ['完全離線', '地下室、露營地、弱網環境，照樣開局。'],
      ['醉酒友好', '更大的觸控區域，更少的操作步驟。'],
      ['14 種玩法', '骰子、抽牌、點名與破冰，一站集齊。'],
    ],
    grid_title_prefix: '派對遊戲',
    grid_title_suffix: 'All-in-One',
    grid_desc: '不管是真心話還是大冒險，一個 App 拯救所有局。',
    cta_main: '告別複雜的規則解釋，',
    cta_highlight: '防誤觸',
    cta_suffix: '設計，讓派對更盡興。',
    cta_lead: '告別複雜的規則解釋',
    cta_badge: '防誤觸設計',
    cta_title: '讓派對更盡興',
    store_badge_lead: '前往',
    btn_download: 'App Store 下載',
    feat_ios: 'iOS 獨佔',
    feat_ads: '無廣告',
    feat_drunk: '防醉酒模式',
    card_hint_front: '點擊查看規則',
    card_hint_back: '點擊返回',
    rules_title: '規則',
    a11y_game_card: '{name}，醉酒指數 {level}，預計時長 {duration}',
    a11y_drunk_level: '醉酒指數 {level} / 5',
    a11y_skip: '跳到主要內容',
    a11y_screens: 'App 截圖',
    a11y_screens_prev: '查看上一張截圖',
    a11y_screens_next: '查看下一張截圖',
    a11y_screens_pagination: '截圖位置指示',
    a11y_screen_menu: '主選單截圖',
    a11y_screen_game: '{name} 遊戲截圖',
    a11y_nav: '主導航',
    a11y_footer: '頁腳',
    a11y_language: '語言',
    footer_rights: '© 2026 CHUGCHUG APP',
    footer_privacy: '隱私政策',
    footer_contact: '聯繫我們',
    inapp_title: '請在 Safari 或預設瀏覽器中打開',
    inapp_subtitle: '檢測到當前處於內置瀏覽器中，無法直接跳轉 App Store',
    inapp_step1_label: '1. 點擊右上角選單按鈕',
    inapp_step1_code: '•••',
    inapp_step2_label: '2. 選擇「在 Safari 中打開」或「在預設瀏覽器中打開」',
    inapp_btn_copy: '複製網頁連結',
    inapp_copied: '已複製連結！',
    inapp_btn_close: '我知道了',
  },
  en: {
    nav_download: 'Download',
    hero_title_1: 'Chug',
    hero_title_2: 'Chug',
    hero_title_3: '',
    hero_subtitle: 'Turn Any Table into a Party.',
    hero_feature: 'Party Essentials · Drunk-Proof · No Awkward Silence',
    hero_points: ['14 games', 'Offline ready', 'No ads'],
    highlights_eyebrow: 'Made for real parties',
    highlights_title: 'Less explaining. More playing.',
    highlights_intro: 'Fast start. No dead air.',
    highlights: [
      ['Open and play', 'Rules and props are ready when you are.'],
      ['Fully offline', 'Basements, campsites, bad signal - still on.'],
      ['Drunk-friendly', 'Larger targets and fewer steps by design.'],
      ['14 ways to play', 'Dice, cards, picks, and icebreakers in one place.'],
    ],
    grid_title_prefix: 'Party Games',
    grid_title_suffix: 'All-in-One',
    grid_desc: 'Truth or Dare or Dice? Save the party with one app.',
    cta_main: 'No more explaining rules.',
    cta_highlight: 'Drunk-Proof',
    cta_suffix: 'design for better parties.',
    cta_lead: 'No more explaining rules',
    cta_badge: 'Drunk-proof by design',
    cta_title: 'Keep the party moving',
    store_badge_lead: 'Download on the',
    btn_download: 'Download on App Store',
    feat_ios: 'iOS Only',
    feat_ads: 'No Ads',
    feat_drunk: 'Drunk Mode',
    card_hint_front: 'Tap for rules',
    card_hint_back: 'Tap to go back',
    rules_title: 'Rules',
    a11y_game_card: '{name}, drunk level {level}, duration {duration}',
    a11y_drunk_level: 'Drunk level {level} of 5',
    a11y_skip: 'Skip to main content',
    a11y_screens: 'App screenshots',
    a11y_screens_prev: 'Previous screenshots',
    a11y_screens_next: 'Next screenshots',
    a11y_screens_pagination: 'Screens position indicator',
    a11y_screen_menu: 'Main menu screenshot',
    a11y_screen_game: '{name} game screenshot',
    a11y_nav: 'Primary',
    a11y_footer: 'Footer',
    a11y_language: 'Language',
    footer_rights: '© 2026 CHUGCHUG APP',
    footer_privacy: 'Privacy',
    footer_contact: 'Contact',
    inapp_title: 'Open in Safari or Default Browser',
    inapp_subtitle: 'In-app browsers cannot open the App Store directly',
    inapp_step1_label: '1. Tap the menu button in top-right corner',
    inapp_step1_code: '•••',
    inapp_step2_label: '2. Select "Open in Safari" or "Open in Browser"',
    inapp_btn_copy: 'Copy Page Link',
    inapp_copied: 'Link Copied!',
    inapp_btn_close: 'Got it',
  },
};
