export const HOME_COPY = {
  zh: {
    nav_download: '下载 App',
    hero_title_1: '吨',
    hero_title_2: '吨',
    hero_title_3: '吨',
    hero_subtitle: '不带道具，也能玩到散场',
    hero_feature: '派对神器 · 防误触 · 拒绝冷场',
    hero_points: ['14 款游戏', '离线可玩', '无广告'],
    grid_title_prefix: '派对游戏',
    grid_title_suffix: 'All-in-One',
    grid_desc: '不管是真心话还是大冒险，\n一个 App 拯救所有局。',
    cta_main: '告别复杂的规则解释，',
    cta_highlight: '防误触',
    cta_suffix: '设计，让派对更尽兴。',
    btn_download: 'App Store 下载',
    feat_ios: 'iOS 独占',
    feat_ads: '无广告',
    feat_drunk: '防醉酒模式',
    card_hint_front: '点击查看规则',
    card_hint_back: '点击返回',
    rules_title: '规则',
    footer_rights: '© 2026 CHUGCHUG APP',
    footer_privacy: '隐私政策',
    footer_contact: '联系我们',
  },
  'zh-Hant': {
    nav_download: '下載 App',
    hero_title_1: 'Chug',
    hero_title_2: 'Chug',
    hero_title_3: '',
    hero_subtitle: '不帶道具，也能玩到散場',
    hero_feature: '派對神器 · 防誤觸 · 拒絕冷場',
    hero_points: ['14 款遊戲', '離線可玩', '無廣告'],
    grid_title_prefix: '派對遊戲',
    grid_title_suffix: 'All-in-One',
    grid_desc: '不管是真心話還是大冒險，\n一個 App 拯救所有局。',
    cta_main: '告別複雜的規則解釋，',
    cta_highlight: '防誤觸',
    cta_suffix: '設計，讓派對更盡興。',
    btn_download: 'App Store 下載',
    feat_ios: 'iOS 獨佔',
    feat_ads: '無廣告',
    feat_drunk: '防醉酒模式',
    card_hint_front: '點擊查看規則',
    card_hint_back: '點擊返回',
    rules_title: '規則',
    footer_rights: '© 2026 CHUGCHUG APP',
    footer_privacy: '隱私政策',
    footer_contact: '聯繫我們',
  },
  en: {
    nav_download: 'Download',
    hero_title_1: 'Chug',
    hero_title_2: 'Chug',
    hero_title_3: '',
    hero_subtitle: 'Turn Any Table into a Party.',
    hero_feature: 'Party Essentials · Drunk-Proof · No Awkward Silence',
    hero_points: ['14 games', 'Offline ready', 'No ads'],
    grid_title_prefix: 'Party Games',
    grid_title_suffix: 'All-in-One',
    grid_desc: 'Truth or Dare or Dice?\nSave the party with one app.',
    cta_main: 'No more explaining rules.',
    cta_highlight: 'Drunk-Proof',
    cta_suffix: 'design for better parties.',
    btn_download: 'Download on App Store',
    feat_ios: 'iOS Only',
    feat_ads: 'No Ads',
    feat_drunk: 'Drunk Mode',
    card_hint_front: 'Tap for rules',
    card_hint_back: 'Tap to go back',
    rules_title: 'Rules',
    footer_rights: '© 2026 CHUGCHUG APP',
    footer_privacy: 'Privacy',
    footer_contact: 'Contact',
  },
};
