export const PRIVACY_COPY = {
  zh: {
    brand: '吨吨吨',
    back: '返回主页',
    title: '隐私政策',
    subtitle:
      'ChugChug（“我们”）非常重视你的隐私。ChugChug 是一款用于线下聚会的本地喝酒游戏 App，设计目标是：无需账号、无需联网、无需收集个人信息即可使用。',
    website_label: 'Website',
    website: 'https://chugchug.app',
    s1: '1. 我们收集的信息',
    s1b:
      '我们不会收集、存储或上传任何可识别个人身份的信息（PII），包括但不限于：',
    s1l1: '姓名、邮箱、电话号码',
    s1l2: '位置信息',
    s1l3: '通讯录',
    s1l4: '照片、音频或视频',
    s1l5: '社交账号或登录信息',
    s1c: '所有游戏内容、随机结果与操作均在用户设备本地完成。',
    s2: '2. 设备权限说明',
    s2b: 'ChugChug 仅使用实现基础功能所需的系统能力，例如：',
    s2l1: '触控 / 屏幕交互：用于游戏操作',
    s2l2: '振动 / 音效（如启用）：用于增强游戏体验',
    s2c: '我们不会请求或访问以下权限：',
    s2d1: '相机',
    s2d2: '麦克风',
    s2d3: '相册',
    s2d4: '通讯录',
    s2d5: '定位信息',
    s3: '3. 第三方服务',
    s3b:
      '目前，ChugChug 不集成任何第三方广告、分析、统计或追踪服务。如果未来引入相关服务，我们将更新本隐私政策并明确说明。',
    s4: '4. 未成年人声明',
    s4b:
      'ChugChug 仅适用于达到当地法定饮酒年龄的用户。我们不会有意收集任何未成年人的信息。',
    s5: '5. 数据安全',
    s5b:
      '由于我们不收集、存储或传输用户的个人数据，因此不存在用户数据被泄露、出售或滥用的风险。',
    s6: '6. 隐私政策的变更',
    s6b:
      '我们可能会不定期更新本隐私政策。更新后的版本将发布在应用内或官方网站上。继续使用本应用即表示你接受更新后的隐私政策。',
    s7: '7. 联系我们',
    s7b: '如果你对本隐私政策有任何疑问，请通过以下方式联系我们：',
  },
  'zh-Hant': {
    brand: 'ChugChug',
    back: '返回主頁',
    title: '隱私政策',
    subtitle:
      'ChugChug（「我們」）非常重視你的隱私。ChugChug 是一款用於線下聚會的本地喝酒遊戲 App，設計目標是：無需帳號、無需聯網、無需收集個人資訊即可使用。',
    website_label: 'Website',
    website: 'https://chugchug.app',
    s1: '1. 我們收集的資訊',
    s1b:
      '我們不會收集、儲存或上傳任何可識別個人身分的資訊（PII），包括但不限於：',
    s1l1: '姓名、郵箱、電話號碼',
    s1l2: '位置資訊',
    s1l3: '通訊錄',
    s1l4: '照片、音訊或影片',
    s1l5: '社交帳號或登入資訊',
    s1c: '所有遊戲內容、隨機結果與操作均在使用者裝置本地完成。',
    s2: '2. 裝置權限說明',
    s2b: 'ChugChug 僅使用實現基礎功能所需的系統能力，例如：',
    s2l1: '觸控 / 螢幕互動：用於遊戲操作',
    s2l2: '震動 / 音效（如啟用）：用於增強遊戲體驗',
    s2c: '我們不會請求或存取以下權限：',
    s2d1: '相機',
    s2d2: '麥克風',
    s2d3: '相簿',
    s2d4: '通訊錄',
    s2d5: '定位資訊',
    s3: '3. 第三方服務',
    s3b:
      '目前，ChugChug 不整合任何第三方廣告、分析、統計或追蹤服務。如果未來引入相關服務，我們將更新本隱私政策並明確說明。',
    s4: '4. 未成年人聲明',
    s4b:
      'ChugChug 僅適用於達到當地法定飲酒年齡的使用者。我們不會有意收集任何未成年人的資訊。',
    s5: '5. 資料安全',
    s5b:
      '由於我們不收集、儲存或傳輸使用者的個人資料，因此不存在使用者資料被洩露、出售或濫用的風險。',
    s6: '6. 隱私政策的變更',
    s6b:
      '我們可能會不定期更新本隱私政策。更新後的版本將發布在應用內或官方網站上。繼續使用本應用即表示你接受更新後的隱私政策。',
    s7: '7. 聯絡我們',
    s7b: '如果你對本隱私政策有任何疑問，請透過以下方式聯絡我們：',
  },
  en: {
    brand: 'ChugChug',
    back: 'Back to Home',
    title: 'Privacy Policy',
    subtitle:
      'ChugChug ("we", "our", or "us") respects your privacy. ChugChug is designed as a local party drinking game app that does not require an account, internet connection, or personal data to function.',
    website_label: 'Website',
    website: 'https://chugchug.app',
    s1: '1. Information We Collect',
    s1b:
      'We do not collect, store, or transmit any personally identifiable information (PII), including but not limited to:',
    s1l1: 'Name, email address, or phone number',
    s1l2: 'Location data',
    s1l3: 'Contacts',
    s1l4: 'Photos, audio, or video',
    s1l5: 'Social media or account information',
    s1c: 'All gameplay, randomization, and interactions occur locally on your device.',
    s2: '2. Device Permissions',
    s2b: 'ChugChug only uses basic system features necessary for gameplay, such as:',
    s2l1: 'Touch input / screen interaction',
    s2l2: 'Haptic feedback or sound effects (if enabled)',
    s2c: 'We do not request or access the following permissions:',
    s2d1: 'Camera',
    s2d2: 'Microphone',
    s2d3: 'Photo library',
    s2d4: 'Contacts',
    s2d5: 'Location services',
    s3: '3. Third-Party Services',
    s3b:
      'ChugChug does not use any third-party advertising, analytics, or tracking services. If this changes in the future, this Privacy Policy will be updated accordingly.',
    s4: '4. Children',
    s4b:
      'ChugChug is intended for users who meet the legal drinking age in their jurisdiction. We do not knowingly collect any information from children.',
    s5: '5. Data Security',
    s5b:
      'Because we do not collect or store personal data, there is no risk of personal data misuse, leakage, or sale.',
    s6: '6. Changes to This Policy',
    s6b:
      'We may update this Privacy Policy from time to time. The updated version will be published within the app or on our website. Continued use of the app indicates acceptance of the updated policy.',
    s7: '7. Contact Us',
    s7b: 'If you have any questions about this Privacy Policy, please contact us:',
  },
};
